# Generated by Django 2.2.24 on 2022-01-15 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0060_auto_20210512_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedThumbnailLarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='curated_thumbs')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
    ]
